# Generated by Django 3.2.7 on 2021-11-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
