# Generated by Django 3.2.7 on 2021-11-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='description',
        ),
    ]
