# Generated by Django 3.2.7 on 2021-09-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_of_create', models.DateTimeField()),
                ('date_of_last_change', models.DateTimeField(null=True)),
                ('text', models.TextField()),
                ('page_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('number_of_articles', models.IntegerField(default=0)),
                ('moderator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport24app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_create', models.DateTimeField()),
                ('date_of_last_change', models.DateTimeField(null=True)),
                ('text', models.TextField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport24app.articles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport24app.users')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport24app.sections'),
        ),
    ]
