# Generated by Django 3.2.7 on 2021-11-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0002_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
