# Generated by Django 3.2.7 on 2021-11-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0002_remove_quote_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quotes',
            new_name='quote',
        ),
    ]
