# Generated by Django 3.2.7 on 2021-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0003_rename_quotes_quote_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
