# Generated by Django 3.2.7 on 2021-11-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_create',
            field=models.CharField(max_length=20),
        ),
    ]
