# Generated by Django 3.2.7 on 2021-11-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0005_alter_article_date_of_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
