# Generated by Django 3.2.9 on 2021-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
