# Generated by Django 3.2.9 on 2022-01-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
