# Generated by Django 3.2.9 on 2022-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
