# Generated by Django 3.2.9 on 2022-01-07 16:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(blank=True, default='ludzik.png', null=True, upload_to=users.models.upload_to_profiles, verbose_name='Image'),
        ),
    ]
