# Generated by Django 3.2.7 on 2021-10-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage='img dyscypliny', upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage='img rozgrywki', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage='images', upload_to=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage='img sekcje', upload_to=''),
        ),
    ]
