# Generated by Django 3.2.7 on 2021-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0002_auto_20211028_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='img sekcje'),
        ),
    ]
