# Generated by Django 3.2.7 on 2021-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0003_alter_section_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='img dyscypliny'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img rozgrywki'),
        ),
    ]
