# Generated by Django 3.2.9 on 2021-12-04 13:38

from django.db import migrations, models
import sport24app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='big_title_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='icon',
            field=models.ImageField(blank=True, default='media/ludzik.png', null=True, upload_to=sport24app.models.upload_to_disciplines, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img rozgrywki', verbose_name='Image'),
        ),
    ]
