# Generated by Django 3.2.9 on 2021-12-04 13:39

from django.db import migrations, models
import sport24app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0002_auto_20211204_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=sport24app.models.upload_to_games, verbose_name='Image'),
        ),
    ]
