# Generated by Django 3.2.9 on 2022-01-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
