# Generated by Django 3.2.9 on 2021-12-04 13:40

from django.db import migrations, models
import sport24app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0003_alter_game_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, default='media/ludzik.png', null=True, upload_to=sport24app.models.upload_to_games, verbose_name='Image'),
        ),
    ]
