# Generated by Django 3.2.9 on 2021-12-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0004_alter_game_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='big_title_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
