# Generated by Django 3.2.9 on 2021-12-04 13:58

from django.db import migrations, models
import sport24app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0006_alter_article_big_title_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='big_title_photo',
            field=models.ImageField(blank=True, default='media/ludzik.png', null=True, upload_to=sport24app.models.upload_to_articles, verbose_name='Image'),
        ),
    ]
