# Generated by Django 3.2.9 on 2021-12-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0008_remove_article_small_title_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='add_photo',
        ),
    ]
