# Generated by Django 3.2.9 on 2021-12-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport24app', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='img sekcje', verbose_name='Image'),
        ),
    ]
